name: "Hello World Workflow"

on: 
    push:
        branches:
            -master
            -production


jobs:
    hello_world:
        runs_on: ubuntu latest
        steps:
            -name: "print jello world"
             run: echo "hello world"

             